feature/server blacklist #7
Dominik48N/party-system pull request #15
Opened 2023-06-01 18:17 UTC by PhantomClone

### Changes Made

- add test for list support in Document
- add ServerSwitchConfigTest
- implement ServerSwitchConfig in ProxyPluginConfig
- create base class for SwitchServer
- add check for black & white list server
- supply serverSwitchConfig for listeners

### Reason for Changes

Include a config entry that allows servers to be blacklisted so that if the party leader joins this server, the party is not pulled along.

It would make sense to support explicit server names, as well as the beginning of a server name. As an example, all servers whose names begin with "Lobby" are directly blacklisted.

### Issues Resolved

Now possible to configurate in config Black and Whitelist for server swapping with enable option

### Checklist

- [ ] I have tested these changes locally
- [X] *(Optional)* I have updated the tests accordingly
- [X] My code follows the established code style guidelines
- [X] I have added/updated necessary comments to my code

2023-06-01 18:38 UTC, Dominik48N commented
Issue: #7

2023-06-01 19:28 UTC, Dominik48N requested changes
Thank you for the pull request!
All in all it looks pretty good! In some places it's just because of the code style.

I'll add to the review as I see you're still working on it. Please use the `Draft Pull Requests` function in the future if you are not finished yet.

2023-06-01 19:28 UTC, Dominik48N commented on common/src/main/java/com/github/dominik48n/party/server/SwitchServer.java
> +    private static boolean isPartyLeader(PartyPlayer player, Party party) {
Useless method - remove this

2023-06-01 19:28 UTC, Dominik48N commented on bungeecord/src/main/java/com/github/dominik48n/party/bungee/listener/SwitchServerListener.java
> +import java.util.logging.Logger;
Please remove the new imports formatting

2023-06-01 19:28 UTC, Dominik48N commented on common/src/test/java/com/github/dominik48n/party/config/DocumentTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Please remove the new import formatting

2023-06-01 19:28 UTC, Dominik48N commented on common/src/test/java/com/github/dominik48n/party/config/DocumentTest.java
> +        List<String> list = of("Value1", "Value2", "Value3");
```suggestion
        final List<String> list = of("Value1", "Value2", "Value3");
```
We want to be sure that the list is not overwritten.

2023-06-01 19:28 UTC, Dominik48N commented on common/src/test/java/com/github/dominik48n/party/config/DocumentTest.java
> +        List<String> retrievedList = document.getList("key", new ArrayList<>(), Document.stringCollector());
```suggestion
        final List<String> retrievedList = document.getList("key", new ArrayList<>(), Document.stringCollector());
```
We want to be sure that the list is not overwritten.

2023-06-01 19:28 UTC, Dominik48N commented on common/src/test/java/com/github/dominik48n/party/config/DocumentTest.java
> +        ArrayNode arrayNode = new ArrayNode(JsonNodeFactory.withExactBigDecimals(false));
```suggestion
        final ArrayNode arrayNode = new ArrayNode(JsonNodeFactory.withExactBigDecimals(false));
```

2023-06-01 19:28 UTC, Dominik48N commented on common/src/main/java/com/github/dominik48n/party/config/SwitchServerConfig.java
> +    private final ConfigList whiteList;
```suggestion
    private final @NotNull ConfigList whiteList;
```

2023-06-01 19:28 UTC, Dominik48N commented on common/src/main/java/com/github/dominik48n/party/config/SwitchServerConfig.java
> +    private final ConfigList blackList;
```suggestion
    private final @NotNull ConfigList blackList;
```

2023-06-01 19:28 UTC, Dominik48N commented on common/src/test/java/com/github/dominik48n/party/server/SwitchServerTest.java
> +package com.github.dominik48n.party.server;
Add copyright header

2023-06-01 19:28 UTC, Dominik48N requested changes
Thank you for the pull request!
All in all it looks pretty good! In some places it's just because of the code style.

I'll add to the review as I see you're still working on it. Please use the `Draft Pull Requests` function in the future if you are not finished yet.

2023-06-01 19:52 UTC, Dominik48N commented
Please also remember to test your update locally!

2023-06-01 20:29 UTC, PhantomClone commented
There is no need for test locally, as long as unit test pass.

I was already done. 
Just added the missing test as the testing engine in gradle is here now. And I didn't want to add my own test build in gradle files before.

2023-06-01 21:31 UTC, Dominik48N requested changes
I still noted the last things. Many thanks for the support!

2023-06-01 21:31 UTC, Dominik48N commented on common/src/test/java/com/github/dominik48n/party/config/SwitchServerConfigTest.java
> +}
Add a last line

2023-06-01 21:31 UTC, Dominik48N commented on common/src/test/java/com/github/dominik48n/party/server/SwitchServerTest.java
> +    void handleServerConnected() throws JsonProcessingException {
Please declare the variables in the method that should not be changed as `final`.

2023-06-01 21:31 UTC, Dominik48N commented on common/src/test/java/com/github/dominik48n/party/server/SwitchServerTest.java
> +    void handleServerConnectedFailBecauseNotMatchWhiteList() throws JsonProcessingException {
Please declare the variables in the method that should not be changed as `final`.

2023-06-01 21:31 UTC, Dominik48N commented on common/src/test/java/com/github/dominik48n/party/server/SwitchServerTest.java
> +    void handleServerConnectedDisableWhiteList() throws JsonProcessingException {
Please declare the variables in the method that should not be changed as `final`.

2023-06-01 21:31 UTC, Dominik48N commented on common/src/test/java/com/github/dominik48n/party/server/SwitchServerTest.java
> +    void handleServerConnectedDisableBlackList() throws JsonProcessingException {
Please declare the variables in the method that should not be changed as `final`.

2023-06-01 21:31 UTC, Dominik48N commented on common/src/test/java/com/github/dominik48n/party/server/SwitchServerTest.java
> +    void handleServerConnectedNotPartyLeader() throws JsonProcessingException {
Please declare the variables in the method that should not be changed as `final`.

2023-06-01 21:31 UTC, Dominik48N commented on common/src/test/java/com/github/dominik48n/party/server/SwitchServerTest.java
> +    public void expectError() throws JsonProcessingException {
Please declare the variables in the method that should not be changed as `final`.

2023-06-01 21:31 UTC, Dominik48N commented on common/src/test/java/com/github/dominik48n/party/server/SwitchServerTest.java
I think it would be useful if the variables that appear in many tests, such as the username or the server name, were declared once in the class instead of in each method again. That saves code.

And please use `this.` when accessing methods or variables from the same class.

2023-06-01 21:31 UTC, Dominik48N commented on common/src/test/java/com/github/dominik48n/party/server/SwitchServerTest.java
> +    //Mockito can not Mock final classes.
```suggestion
    // Mockito can not Mock final classes.
```

2023-06-01 21:31 UTC, Dominik48N commented on common/src/test/java/com/github/dominik48n/party/server/SwitchServerTest.java
> +    private SwitchServer<String> createSwitchServer() {
```suggestion
    private @NotNull SwitchServer<String> createSwitchServer() {
```

2023-06-01 21:31 UTC, Dominik48N commented on common/src/test/java/com/github/dominik48n/party/server/SwitchServerTest.java
> +            public void logJsonProcessingException(JsonProcessingException jsonProcessingException) { }
```suggestion
            public void logJsonProcessingException(final @Nullable JsonProcessingException exception) { }
```

2023-06-02 22:00 UTC, Dominik48N requested changes
I removed the public test methods from the project today, please reconcile this in your test methods and remove the public test methods to keep this consistent.

Please use `this.` when accessing variables or methods from the same class. Please fix that in the tests.

2023-06-02 22:04 UTC, Dominik48N commented
Please remember to resolve the conversations when you've made the changes, and if you have any complaints about any change I'm proposing, please post that in the appropriate conversation as well.

2023-06-03 10:58 UTC, Dominik48N requested changes
Please do not request the next review until you have suggested the changes.

If you have any objection to a change I've suggested, please respond in the appropriate conversation. Please indicate the changes you have made with the appropriate `resolve conversation`.

2023-06-03 10:58 UTC, Dominik48N commented on common/src/main/java/com/github/dominik48n/party/server/SwitchServer.java
> +    public abstract void logJsonProcessingException(@NotNull final JsonProcessingException jsonProcessingException);
```suggestion
    public abstract void logJsonProcessingException(final @NotNull JsonProcessingException exception);
```

2023-06-03 10:58 UTC, Dominik48N commented on common/src/main/java/com/github/dominik48n/party/server/SwitchServer.java
> +    private static boolean isPartyLeader(final @NotNull PartyPlayer player, final @NotNull Party party) {
Remove this useless method

2023-06-03 10:58 UTC, Dominik48N commented on common/src/test/java/com/github/dominik48n/party/config/SwitchServerConfigTest.java
> +        this.config = createConfig(this.whiteRegex, this.blackRegex);
```suggestion
        this.config = this.createConfig(this.whiteRegex, this.blackRegex);
```

2023-06-03 10:58 UTC, Dominik48N commented on common/src/test/java/com/github/dominik48n/party/server/SwitchServerTest.java
> +        setPartyProvider();
```suggestion
        this.setPartyProvider();
```

2023-06-03 10:58 UTC, Dominik48N commented on common/src/test/java/com/github/dominik48n/party/server/SwitchServerTest.java
> +        switchServer = createSwitchServer();
```suggestion
        this.switchServer = this.createSwitchServer();
```

2023-07-19 00:27 UTC, Dominik48N commented
In the last push on the master branch, string lists for the configs were added. Please use this and please think about the pending change requests. :)

2023-07-30 18:48 UTC, PhantomClone commented
I am no longer working on the project

2023-07-30 18:48 UTC, closed without merging